#define  IR_RECEIVE_PIN 15
#define R 5
#define G 6
#define B 9
#define IR_PIN 11
#define POWER_BUTT 48
#define OPEN/CLOSE_BUTT 54
#define TV_POWER_BUTT 8
#define BUTT_1 59
#define BUTT_2 60
#define BUTT_3 61
#define BUTT_4 62
#define BUTT_5 63
#define BUTT_6 64
#define BUTT_7 65
#define BUTT_8 66
#define BUTT_9 67
#define CLEAR_BUTT 70
#define BUTT_0 68
#define AV_BUTT 11
#define CH+_BUTT 0
#define CH-_BUTT 1
#define VOL+_BUTT 2
#define VOL-_BUTT 3
#define SCAN<<_BUTT 50
#define SCAN>>_BUTT 51
#define SKIP<<_BUTT 53
#define SKIP>>_BUTT 52
#define PAUSE_BUTT 56
#define PLAY_BUTT 49
#define STOP_BUTT 57
#define DVD_MENU_BUTT 75
#define TITLE_BUTT 74
#define UP_BUTT1 71
#define LEFT_BUTT1 89
#define RIGHT_BUTT1 90
#define DOWN_BUTT1 72
#define ENTER_BUTT 88
#define DISPLAY_BUTT 58
#define RETURN_BUTT 69
#define AUDIO_BUTT 79
#define SUBTITLE_BUTT 80
#define ANGLE_BUTT 76
#define SETUP_BUTT 86
#define MARKER_BUTT 97
#define SEARCH_BUTT 98
#define PROGRAM_BUTT 87
#define ZOOM_BUTT 100
#define REPEAT_BUTT 83
#define A_B_BUTT 85
#define RANDOM_BUTT 81
#define STAR_BUTT 94
#define RESPONSE_TIME 10
#define ON 0
#define OFF 1
#define INCREASE_RATE 5 
//variables declare
#define rBUTT_1 59
#define rBUTT_2 60
#define rSCAN1BUTT 50
#define rSCAN2BUTT 51
#define rUP_BUTT1 71
#define rLEFT_BUTT1 89
#define rRIGHT_BUTT1 90
#define rDOWN_BUTT1 72
#define rENTER_BUTT1 88
#define rRETURN_BUTT1 69
#define rVOL1BUTT 2
#define rVOL2BUTT 3

#define LEFTCLICK 1
#define RIGHTCLICK 2

#include <IRremote.h>
#include <SPI.h>
#include <Wire.h>
#include <Adafruit_GFX.h>
#include <Adafruit_SSD1306.h>

#define A 1
#define B 2
#define C 3
#define D 4
#define E 5
#define F 6
#define G 7
#define H 8
#define I 9
#define J 10
#define K 11
#define L 12
#define M 13
#define N 14
#define O 15
#define P 16
#define Q 17
#define R 18
#define S 19
#define T 20
#define U 21
#define V 22
#define W 23
#define X 24
#define Y 25
#define Z 26
